# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Book

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Node Dependencies
        run: yarn install
      - name: Build Book
        run: yarn build