# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Book

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install Dependencies
        run: yarn Install
      - run: yarn build
      - run: yarn test